apiVersion: v1
kind: Secret
metadata:
  name: wio-api
  namespace: wio
type: Opaque
stringData:
  POSTGRES_USER: wio
  POSTGRES_PASSWORD: CHANGE_ME
  POSTGRES_DB: wio
  TYPEORM_USERNAME: wio
  TYPEORM_PASSWORD: CHANGE_ME
  DATABASE_URL: postgresql://wio:CHANGE_ME@postgres:5432/wio
  REDIS_PASSWORD: CHANGE_ME
  JWT_SECRET: CHANGE_ME_64_CHAR
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  FACEBOOK_APP_ID: ""
  FACEBOOK_APP_SECRET: ""
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
