export const enumData = {
  GENDER: {
    MALE: { code: 'MALE', name: 'Nam' },
    FEMALE: { code: 'FEMALE', name: 'Nữ' },
    OTHER: { code: 'OTHER', name: 'Khác' },
  },

  ACTION_TYPE: {
    CREATE: { code: 'CREATE', name: 'Thêm mới', type: 'ThemMoi' },
    DELETE: { code: 'DELETE', name: 'Xoá bỏ', type: 'XoaBo' },
    UPDATE: { code: 'UPDATE', name: 'Cập nhật', type: 'CapNhat' },
    SYNC: { code: 'SYNC', name: 'Đồng bộ', type: 'DongBo' },
    EDIT: { code: 'EDIT', name: 'Chỉnh sửa', type: 'ChinhSua' },
    APPROVE: { code: 'APPROVE', name: 'Duyệt', type: 'Duyet' },
    SEND_APPROVE: { code: 'SEND_APPROVE', name: 'Gửi duyệt', type: 'GuiDuyet' },
    REJECT: { code: 'REJECT', name: 'Từ chối', type: 'TuChoi' },
    CANCEL: { code: 'CANCEL', name: 'Huỷ', type: 'Huy' },
    IMPORT_EXCEL: {
      code: 'IMPORT_EXCEL',
      name: 'Nhập excel',
      type: 'NhapExcel',
    },
    ACTIVATE: { code: 'ACTIVATE', name: 'Kích hoạt', type: 'KichHoat' },
    DEACTIVATE: {
      code: 'DEACTIVATE',
      name: 'Ngưng hoạt động',
      type: 'NgungHoatDong',
    },
    RESTORE: { code: 'RESTORE', name: 'Khôi phục', type: 'KhoiPhuc' },
    AWARD: { code: 'AWARD', name: 'Trao thưởng', type: 'TraoThuong' },
    LOGIN: { code: 'LOGIN', name: 'Đăng nhập', type: 'DangNhap' },
    LOGOUT: { code: 'LOGOUT', name: 'Đăng xuất', type: 'DangXuat' },
    REGISTER: { code: 'REGISTER', name: 'Đăng ký', type: 'DangKy' },
    UPLOAD_FILE: {
      code: 'UPLOAD_FILE',
      name: 'Tải file lên',
      type: 'TaiFileLen',
    },
    CREATE_EXAM: { code: 'CREATE_EXAM', name: 'Tạo đề thi', type: 'TaoDeThi' },
    SUBMIT_EXAM: {
      code: 'SUBMIT_EXAM',
      name: 'Nộp bài thi',
      type: 'NopBaiThi',
    },
    GRADE_EXAM: { code: 'GRADE_EXAM', name: 'Chấm thi', type: 'ChamThi' },
    PUBLISH: { code: 'PUBLISH', name: 'Xuất bản', type: 'XuatBan' },
    UNPUBLISH: { code: 'UNPUBLISH', name: 'Huỷ xuất bản', type: 'HuyXuatBan' },
    COMMENT: { code: 'COMMENT', name: 'Bình luận', type: 'BinhLuan' },
    APPROVE_COMMENT: {
      code: 'APPROVE_COMMENT',
      name: 'Duyệt bình luận',
      type: 'DuyetBinhLuan',
    },
    SEND_NOTIFICATION: {
      code: 'SEND_NOTIFICATION',
      name: 'Gửi thông báo',
      type: 'GuiThongBao',
    },
  },
};
