import { MigrationInterface, QueryRunner } from "typeorm";

export class InitData1789651847982 implements MigrationInterface {
    name = 'InitData1789651847982'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "ai_scan_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "userId" uuid NOT NULL, "sourceImageUrl" text NOT NULL, "sourceStorageKey" character varying(500), "status" character varying(30) NOT NULL, "provider" character varying(50), "result" jsonb, "designTokens" jsonb, "errorMessage" text, "retryCount" integer NOT NULL DEFAULT '0', "startedAt" TIMESTAMP WITH TIME ZONE, "finishedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_9ed213080ecfb0cf3dc3b0ed9e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8301ce4e44fd008d3fa52b1082" ON "ai_scan_jobs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_979d68c15b9cfa630e4e7b079a" ON "ai_scan_jobs" ("invitationId", "status") `);
        await queryRunner.query(`CREATE TABLE "invitation_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "eventKey" character varying(40) NOT NULL, "title" character varying(255) NOT NULL, "startsAt" TIMESTAMP WITH TIME ZONE, "endsAt" TIMESTAMP WITH TIME ZONE, "venue" character varying(255), "address" text, "mapsUrl" text, "lat" numeric(10,7), "lng" numeric(10,7), "dressCode" text, "isPrimary" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_aeba8a6698698075fe9a2656bdb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3be57c9efcf3f5d3e1f29b60ba" ON "invitation_events" ("invitationId", "isPrimary") `);
        await queryRunner.query(`CREATE TABLE "invitation_gifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "label" character varying(150) NOT NULL, "bankName" character varying(100), "accountNumber" character varying(50), "accountOwner" character varying(100), "qrUrl" text, "side" character varying(20), "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_8049051d42c5ad342cc2232b533" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invitation_hosts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "role" character varying(40) NOT NULL, "fullName" character varying(150) NOT NULL, "shortName" character varying(80), "photoUrl" text, "social" jsonb, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_88a9ee5697374f129a2b479f9bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_83a30ca2423c78e0368edca192" ON "invitation_hosts" ("invitationId", "role") `);
        await queryRunner.query(`CREATE TABLE "invitation_photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "url" text NOT NULL, "storageKey" character varying(500), "caption" character varying(255), "kind" character varying(20) NOT NULL DEFAULT 'GALLERY', "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_bb45b80161823427aa08db2deff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4b935a633d89d654d89fe61146" ON "invitation_photos" ("invitationId", "kind") `);
        await queryRunner.query(`CREATE TABLE "invitation_timelines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "eventId" uuid, "timeLabel" character varying(50), "title" character varying(255) NOT NULL, "description" text, "iconUrl" text, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_d846abafc2715c9fa39d3970bfb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e4f80ce3e8c902a041a0e67e9e" ON "invitation_timelines" ("invitationId", "sortOrder") `);
        await queryRunner.query(`CREATE TABLE "invitation_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "versionNumber" integer NOT NULL, "snapshot" jsonb NOT NULL, "note" character varying(255), "createdByUserId" uuid, CONSTRAINT "PK_cf1365405d56418958cac66734e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_398c05e4d6bf462a564518d763" ON "invitation_versions" ("invitationId", "versionNumber") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "guestId" uuid, "channel" character varying(20) NOT NULL, "type" character varying(40) NOT NULL, "subject" character varying(255), "content" text NOT NULL, "status" character varying(20) NOT NULL, "scheduledAt" TIMESTAMP WITH TIME ZONE NOT NULL, "sentAt" TIMESTAMP WITH TIME ZONE, "failedReason" text, "provider" character varying(50), "providerMsgId" character varying(255), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54e1725163ede8bf2ce08874a6" ON "notifications" ("guestId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab221329a9f4c2111690d52f34" ON "notifications" ("scheduledAt", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bbc7822f5247b7de25eee9f0a2" ON "notifications" ("invitationId", "status") `);
        await queryRunner.query(`CREATE TABLE "photo_wall" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "guestId" uuid, "uploaderName" character varying(100) NOT NULL, "url" text NOT NULL, "storageKey" character varying(500), "caption" character varying(255), "isApproved" boolean NOT NULL DEFAULT true, "approvedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f855d3c717415b24d8e3ad64136" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cce2a297871b91702b702bac2b" ON "photo_wall" ("invitationId", "isApproved") `);
        await queryRunner.query(`CREATE TABLE "slug_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "oldSlug" character varying(100) NOT NULL, "newSlug" character varying(100) NOT NULL, "changedBy" uuid NOT NULL, "reason" text, CONSTRAINT "PK_8a2ec7e164f496a7b5ecd3bb335" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_09ad80453a68e6263e0b73b36a" ON "slug_history" ("invitationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4b0dd06eb0a7ea914010d769c0" ON "slug_history" ("oldSlug") `);
        await queryRunner.query(`CREATE TABLE "tables" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "name" character varying(50) NOT NULL, "maxSeats" smallint NOT NULL DEFAULT '10', "currentSeats" smallint NOT NULL DEFAULT '0', "description" character varying(255), "positionX" integer, "positionY" integer, CONSTRAINT "PK_7cf2aca7af9550742f855d4eb69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dad6ad57fb4c094eea69aa9545" ON "tables" ("invitationId", "name") `);
        await queryRunner.query(`CREATE TABLE "service_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(50) NOT NULL, "code" character varying(20) NOT NULL, "maxInvitations" integer NOT NULL DEFAULT '1', "maxGuests" integer NOT NULL, "maxPhotos" integer NOT NULL, "hasAi" boolean NOT NULL DEFAULT false, "hasAnalytics" boolean NOT NULL DEFAULT false, "hasCustomSlug" boolean NOT NULL DEFAULT false, "hasCustomDesign" boolean NOT NULL DEFAULT false, "durationDays" integer NOT NULL, "priceVnd" bigint NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_679a9e435f1af95a94d9749a087" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dbb3471dd14e54f1727bcc65ae" ON "service_plans" ("isActive") `);
        await queryRunner.query(`CREATE TABLE "template_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "templateId" uuid NOT NULL, "category" character varying(30) NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_ddd88953a0cd7ee62295a90f984" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_973b09cc0fcf86dd20e05f9754" ON "template_categories" ("templateId", "category") `);
        await queryRunner.query(`CREATE TABLE "templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "description" character varying(255), "slug" character varying(100) NOT NULL, "weddingTheme" character varying(30) NOT NULL DEFAULT 'CLASSIC', "tags" text, "colorMood" character varying(50), "features" jsonb, "themeLayout" jsonb, "presetTokens" jsonb, "thumbnailUrl" text, "previewUrl" text, "themeCode" character varying(100) NOT NULL, "isShow" boolean NOT NULL DEFAULT true, "isPremium" boolean NOT NULL DEFAULT false, "min_plan_id" uuid, "trialDays" integer NOT NULL DEFAULT '3', "viewCount" integer NOT NULL DEFAULT '0', "usedCount" integer NOT NULL DEFAULT '0', "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_515948649ce0bbbe391de702ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_12dbb5f2171a62868cb63fac92" ON "templates" ("weddingTheme", "isShow") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fc78f7cf6d378b2410b6192788" ON "templates" ("slug") WHERE "isDeleted" = false`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "code" character varying(50), "fullName" character varying(100) NOT NULL, "email" character varying(255), "phone" character varying(20), "gender" character varying(10), "dateOfBirth" date, "avatarUrl" text, CONSTRAINT "UQ_b8512aa9cef03d90ed5744c94d7" UNIQUE ("userId"), CONSTRAINT "REL_b8512aa9cef03d90ed5744c94d" UNIQUE ("userId"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "password" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20), "role" character varying(20) NOT NULL DEFAULT 'CUSTOMER', "isActive" boolean NOT NULL DEFAULT true, "lastLogin" TIMESTAMP WITH TIME ZONE, "refreshToken" text, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wedding_infos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "brideName" character varying(150) NOT NULL, "brideShortName" character varying(150), "bridePhotoUrl" text, "brideFatherName" character varying(100), "brideMotherName" character varying(100), "brideBio" text, "brideSocial" jsonb, "groomName" character varying(150) NOT NULL, "groomShortName" character varying(150), "groomPhotoUrl" text, "groomFatherName" character varying(100), "groomMotherName" character varying(100), "groomBio" text, "groomSocial" jsonb, "loveStartedAt" TIMESTAMP WITH TIME ZONE, "loveStory" text, "hashtag" character varying(80), CONSTRAINT "UQ_9433528615849320f9251d620f9" UNIQUE ("invitationId"), CONSTRAINT "REL_9433528615849320f9251d620f" UNIQUE ("invitationId"), CONSTRAINT "PK_4a731ab4e966153a804453c1d1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "designMode" character varying(20) NOT NULL DEFAULT 'TEMPLATE', "weddingTheme" character varying(30) NOT NULL, "templateId" uuid, "title" character varying(200) NOT NULL, "slug" character varying(100) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'DRAFT', "invitationText" text, "thankYouText" text, "heroImageUrl" text, "primaryEventAt" TIMESTAMP WITH TIME ZONE, "sectionConfig" jsonb, "musicId" uuid, "musicConfig" jsonb, "customDesign" jsonb, "aiGeneratedMeta" jsonb, "shareUrl" text, "shareQrUrl" text, "seoTitle" character varying(255), "seoDescription" text, "viewCount" integer NOT NULL DEFAULT '0', "uniqueViewCount" integer NOT NULL DEFAULT '0', "publishedAt" TIMESTAMP WITH TIME ZONE, "expiresAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_5dec98cfdfd562e4ad3648bbb07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c16fdad3aea7ec7b047aedb9af" ON "invitations" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dab5f55eaf6f40cb5015f5c34c" ON "invitations" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_56ce8d405de7cdcedd31d900ba" ON "invitations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bf63ca087f62a08e403cb8258" ON "invitations" ("primaryEventAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c3334b2f522e2188b447a68193" ON "invitations" ("userId", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_invitation_slug" ON "invitations" ("slug") WHERE "status" != 'ARCHIVED' AND "isDeleted" = false`);
        await queryRunner.query(`CREATE TABLE "guest_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "code" character varying(40) NOT NULL, "name" character varying(80) NOT NULL, "side" character varying(20), "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_4fbeadf123f31f44b0be0c5414e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ed52cb9300a8b796b68fa6e9f0" ON "guest_groups" ("invitationId", "code") WHERE "isDeleted" = false`);
        await queryRunner.query(`CREATE TABLE "guests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "groupId" uuid, "tableId" uuid, "fullName" character varying(100) NOT NULL, "salutation" character varying(20), "isVip" boolean NOT NULL DEFAULT false, "invitationCode" character varying(32) NOT NULL, "qrCodeUrl" text, "rsvpStatus" character varying(20) NOT NULL, "attendingCount" smallint NOT NULL DEFAULT '1', "needsTransport" boolean NOT NULL DEFAULT false, "rsvpNote" text, "rsvpAt" TIMESTAMP WITH TIME ZONE, "invitedAt" TIMESTAMP WITH TIME ZONE, "invitationViewedAt" TIMESTAMP WITH TIME ZONE, "checkedInAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_47425d181c5b741f25e948e37d5" UNIQUE ("invitationCode"), CONSTRAINT "PK_4948267e93869ddcc6b340a2c46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_47425d181c5b741f25e948e37d" ON "guests" ("invitationCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e682d8a5a84d9944c855b3a26" ON "guests" ("invitationId", "tableId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4dad362db08430c140877baae" ON "guests" ("invitationId", "rsvpStatus") `);
        await queryRunner.query(`CREATE TABLE "wishes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "invitationId" uuid NOT NULL, "guestId" uuid, "guestName" character varying(100) NOT NULL, "content" text NOT NULL, "isApproved" boolean NOT NULL DEFAULT true, "isPinned" boolean NOT NULL DEFAULT false, "approvedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_9c08d144e42ca0aa37a024597ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e567802a4d82e32ae7e00dae2e" ON "wishes" ("invitationId", "isApproved") `);
        await queryRunner.query(`CREATE TABLE "verify_otps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "identifier" character varying(255) NOT NULL, "otpCode" character varying(10) NOT NULL, "method" character varying(20) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "isVerified" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_0d71e8ff7eee7844831e3f3af55" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e5877252ca5d2948b4d0be9486" ON "verify_otps" ("identifier", "otpCode") `);
        await queryRunner.query(`CREATE TABLE "user_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid, "accessToken" text, "refreshToken" text, "ipAddress" character varying(50), "userAgent" character varying(255), "expiresAt" TIMESTAMP WITH TIME ZONE, "isRevoked" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_63764db9d9aaa4af33e07b2f4bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87c817609844d8eb4400589a95" ON "user_tokens" ("userId", "isRevoked") `);
        await queryRunner.query(`CREATE TABLE "promotions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "code" character varying(50) NOT NULL, "name" character varying(150) NOT NULL, "discountType" character varying(20) NOT NULL, "discountValue" bigint NOT NULL, "minOrderVnd" bigint, "maxUses" integer, "usedCount" integer NOT NULL DEFAULT '0', "startsAt" TIMESTAMP WITH TIME ZONE, "endsAt" TIMESTAMP WITH TIME ZONE, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_380cecbbe3ac11f0e5a7c452c34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1f848fbba60ff2d810103066b6" ON "promotions" ("code") WHERE "isDeleted" = false`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "planId" uuid NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', "startedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f2a37d226c4f58242548e53c6b" ON "subscriptions" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_df76e81987c46fdacee7c6dcdc" ON "subscriptions" ("status", "expiresAt") `);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "subscriptionId" uuid, "promotionId" uuid, "amountVnd" bigint NOT NULL, "discountVnd" bigint NOT NULL DEFAULT '0', "method" character varying(30) NOT NULL, "status" character varying(30) NOT NULL, "providerRef" character varying(255), "rawPayload" jsonb, "paidAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6bb58f2b6e30cb51a6504599f4" ON "transactions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_da87c55b3bbbe96c6ed88ea7ee" ON "transactions" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1ba7414cfad49c97d1c567e295" ON "transactions" ("providerRef") WHERE "providerRef" IS NOT NULL AND "isDeleted" = false`);
        await queryRunner.query(`CREATE TABLE "stock_assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "title" character varying(150) NOT NULL, "category" character varying(40) NOT NULL, "tags" text, "src" text NOT NULL, "thumb" text, "kind" character varying(20) NOT NULL, "license" character varying(120), "sortOrder" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_202a30cde62fa6ab0f74aaadc1f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1c84c3e7cdd37d56bb4bef7c21" ON "stock_assets" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2093e81ee39b2202416b3d409" ON "stock_assets" ("kind") `);
        await queryRunner.query(`CREATE INDEX "IDX_stock_asset_kind_active" ON "stock_assets" ("kind", "isActive", "sortOrder") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "authorName" character varying(150) NOT NULL, "content" text NOT NULL, "rating" smallint NOT NULL, "eventLabel" character varying(150), "avatarUrl" text, "weddingTheme" character varying(30), "invitationId" uuid, "userId" uuid, "status" character varying(20) NOT NULL DEFAULT 'PENDING', "isPinned" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7998143b53b0743178739b02fe" ON "reviews" ("invitationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b06c23cf52ca8aea0dcaf0ee2" ON "reviews" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_review_status_pinned" ON "reviews" ("status", "isPinned", "sortOrder") `);
        await queryRunner.query(`CREATE TABLE "music_backgrounds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "author" character varying(255), "duration" character varying(50), "usageCount" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "status" character varying(20) NOT NULL, "youtubeUrl" text, "audioUrl" text, "thumbnailUrl" text, "type" character varying(20) NOT NULL DEFAULT 'UPLOAD', CONSTRAINT "PK_9715fb49ec7050470fb1521db7b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_64bf2470fc515f286e51d21621" ON "music_backgrounds" ("isActive", "type") `);
        await queryRunner.query(`CREATE TABLE "contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "code" character varying(50), "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(50), "subject" character varying(255), "message" text NOT NULL, "status" character varying(20) NOT NULL, "admin_note" text, "responded_at" TIMESTAMP WITH TIME ZONE, "responded_by" uuid, CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b5ac1a37a1c1b494085e28d31" ON "contacts" ("status", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "action-logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdBy" uuid, "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now(), "updatedBy" uuid, "isDeleted" boolean NOT NULL DEFAULT false, "deletedAt" TIMESTAMP WITH TIME ZONE, "createdById" uuid NOT NULL, "createdByCode" character varying(255) NOT NULL, "createdByName" character varying(255) NOT NULL, "createdNote" text, "actionType" character varying(255), "entityId" uuid, "entityName" character varying(255), "oldValue" jsonb, "newValue" jsonb, "ipAddress" character varying(255), "userAgent" text, "location" character varying(255), CONSTRAINT "PK_ffb219d8978756f5e8cfd9e7efe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d2a2f4c3732961897664d17e05" ON "action-logs" ("createdById", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_12dd414abc0ab1281593096e52" ON "action-logs" ("entityName", "entityId") `);
        await queryRunner.query(`ALTER TABLE "ai_scan_jobs" ADD CONSTRAINT "FK_3365c5a5bd3142b98105364fe62" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation_events" ADD CONSTRAINT "FK_02378750243ae0c825ef32a8fec" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation_gifts" ADD CONSTRAINT "FK_a4e94ef50b4f1b0e1dae4deb88a" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation_hosts" ADD CONSTRAINT "FK_407188bc456f9fdadfff3d88d4f" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation_photos" ADD CONSTRAINT "FK_4c548a684f28a2dff1e63da1707" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation_timelines" ADD CONSTRAINT "FK_85030085c2a167ec4fe3dbf2268" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation_versions" ADD CONSTRAINT "FK_aa326591d8a8272b37ece60e33e" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_fd3bc115cd2466d6fb94cde5f4e" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_54e1725163ede8bf2ce08874a67" FOREIGN KEY ("guestId") REFERENCES "guests"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photo_wall" ADD CONSTRAINT "FK_dd81572da219f9ad21086a8d2fc" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photo_wall" ADD CONSTRAINT "FK_d5c1c5b6df974957500ab7fa8dc" FOREIGN KEY ("guestId") REFERENCES "guests"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "slug_history" ADD CONSTRAINT "FK_09ad80453a68e6263e0b73b36a9" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tables" ADD CONSTRAINT "FK_62c8a1d4d23e7cc6a5acbb41df8" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "template_categories" ADD CONSTRAINT "FK_1b476c1771d0790044cf7e6e887" FOREIGN KEY ("templateId") REFERENCES "templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "templates" ADD CONSTRAINT "FK_c1e091ac12afc10334ed795688b" FOREIGN KEY ("min_plan_id") REFERENCES "service_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_b8512aa9cef03d90ed5744c94d7" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wedding_infos" ADD CONSTRAINT "FK_9433528615849320f9251d620f9" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_c16fdad3aea7ec7b047aedb9afe" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_0aad0a3d2486c04dea163f7fe51" FOREIGN KEY ("templateId") REFERENCES "templates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guest_groups" ADD CONSTRAINT "FK_cef580ad342dab959ccb6f78bd2" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guests" ADD CONSTRAINT "FK_f1a1e3ce7ddcd20c0d27a61b86b" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guests" ADD CONSTRAINT "FK_f52db5017ebcff092698d22ea0c" FOREIGN KEY ("groupId") REFERENCES "guest_groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guests" ADD CONSTRAINT "FK_6480f9e34b521067db2cd1bb9f9" FOREIGN KEY ("tableId") REFERENCES "tables"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishes" ADD CONSTRAINT "FK_fa7fc3b5894150c3e66c0763eed" FOREIGN KEY ("invitationId") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishes" ADD CONSTRAINT "FK_271f7466ea8e39fef2e10f1129b" FOREIGN KEY ("guestId") REFERENCES "guests"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7536cba909dd7584a4640cad7d5" FOREIGN KEY ("planId") REFERENCES "service_plans"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_68b3182f3f5d4d5a0f41c12139b" FOREIGN KEY ("subscriptionId") REFERENCES "subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_702c945623383dc1c80a8095bdf" FOREIGN KEY ("promotionId") REFERENCES "promotions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_702c945623383dc1c80a8095bdf"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_68b3182f3f5d4d5a0f41c12139b"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7536cba909dd7584a4640cad7d5"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_fbdba4e2ac694cf8c9cecf4dc84"`);
        await queryRunner.query(`ALTER TABLE "wishes" DROP CONSTRAINT "FK_271f7466ea8e39fef2e10f1129b"`);
        await queryRunner.query(`ALTER TABLE "wishes" DROP CONSTRAINT "FK_fa7fc3b5894150c3e66c0763eed"`);
        await queryRunner.query(`ALTER TABLE "guests" DROP CONSTRAINT "FK_6480f9e34b521067db2cd1bb9f9"`);
        await queryRunner.query(`ALTER TABLE "guests" DROP CONSTRAINT "FK_f52db5017ebcff092698d22ea0c"`);
        await queryRunner.query(`ALTER TABLE "guests" DROP CONSTRAINT "FK_f1a1e3ce7ddcd20c0d27a61b86b"`);
        await queryRunner.query(`ALTER TABLE "guest_groups" DROP CONSTRAINT "FK_cef580ad342dab959ccb6f78bd2"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_0aad0a3d2486c04dea163f7fe51"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_c16fdad3aea7ec7b047aedb9afe"`);
        await queryRunner.query(`ALTER TABLE "wedding_infos" DROP CONSTRAINT "FK_9433528615849320f9251d620f9"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_b8512aa9cef03d90ed5744c94d7"`);
        await queryRunner.query(`ALTER TABLE "templates" DROP CONSTRAINT "FK_c1e091ac12afc10334ed795688b"`);
        await queryRunner.query(`ALTER TABLE "template_categories" DROP CONSTRAINT "FK_1b476c1771d0790044cf7e6e887"`);
        await queryRunner.query(`ALTER TABLE "tables" DROP CONSTRAINT "FK_62c8a1d4d23e7cc6a5acbb41df8"`);
        await queryRunner.query(`ALTER TABLE "slug_history" DROP CONSTRAINT "FK_09ad80453a68e6263e0b73b36a9"`);
        await queryRunner.query(`ALTER TABLE "photo_wall" DROP CONSTRAINT "FK_d5c1c5b6df974957500ab7fa8dc"`);
        await queryRunner.query(`ALTER TABLE "photo_wall" DROP CONSTRAINT "FK_dd81572da219f9ad21086a8d2fc"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_54e1725163ede8bf2ce08874a67"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_fd3bc115cd2466d6fb94cde5f4e"`);
        await queryRunner.query(`ALTER TABLE "invitation_versions" DROP CONSTRAINT "FK_aa326591d8a8272b37ece60e33e"`);
        await queryRunner.query(`ALTER TABLE "invitation_timelines" DROP CONSTRAINT "FK_85030085c2a167ec4fe3dbf2268"`);
        await queryRunner.query(`ALTER TABLE "invitation_photos" DROP CONSTRAINT "FK_4c548a684f28a2dff1e63da1707"`);
        await queryRunner.query(`ALTER TABLE "invitation_hosts" DROP CONSTRAINT "FK_407188bc456f9fdadfff3d88d4f"`);
        await queryRunner.query(`ALTER TABLE "invitation_gifts" DROP CONSTRAINT "FK_a4e94ef50b4f1b0e1dae4deb88a"`);
        await queryRunner.query(`ALTER TABLE "invitation_events" DROP CONSTRAINT "FK_02378750243ae0c825ef32a8fec"`);
        await queryRunner.query(`ALTER TABLE "ai_scan_jobs" DROP CONSTRAINT "FK_3365c5a5bd3142b98105364fe62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12dd414abc0ab1281593096e52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2a2f4c3732961897664d17e05"`);
        await queryRunner.query(`DROP TABLE "action-logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b5ac1a37a1c1b494085e28d31"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64bf2470fc515f286e51d21621"`);
        await queryRunner.query(`DROP TABLE "music_backgrounds"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_review_status_pinned"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b06c23cf52ca8aea0dcaf0ee2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7998143b53b0743178739b02fe"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stock_asset_kind_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2093e81ee39b2202416b3d409"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c84c3e7cdd37d56bb4bef7c21"`);
        await queryRunner.query(`DROP TABLE "stock_assets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ba7414cfad49c97d1c567e295"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da87c55b3bbbe96c6ed88ea7ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bb58f2b6e30cb51a6504599f4"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df76e81987c46fdacee7c6dcdc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2a37d226c4f58242548e53c6b"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f848fbba60ff2d810103066b6"`);
        await queryRunner.query(`DROP TABLE "promotions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87c817609844d8eb4400589a95"`);
        await queryRunner.query(`DROP TABLE "user_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5877252ca5d2948b4d0be9486"`);
        await queryRunner.query(`DROP TABLE "verify_otps"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e567802a4d82e32ae7e00dae2e"`);
        await queryRunner.query(`DROP TABLE "wishes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4dad362db08430c140877baae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e682d8a5a84d9944c855b3a26"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47425d181c5b741f25e948e37d"`);
        await queryRunner.query(`DROP TABLE "guests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed52cb9300a8b796b68fa6e9f0"`);
        await queryRunner.query(`DROP TABLE "guest_groups"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_invitation_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3334b2f522e2188b447a68193"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bf63ca087f62a08e403cb8258"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56ce8d405de7cdcedd31d900ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dab5f55eaf6f40cb5015f5c34c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c16fdad3aea7ec7b047aedb9af"`);
        await queryRunner.query(`DROP TABLE "invitations"`);
        await queryRunner.query(`DROP TABLE "wedding_infos"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc78f7cf6d378b2410b6192788"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12dbb5f2171a62868cb63fac92"`);
        await queryRunner.query(`DROP TABLE "templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_973b09cc0fcf86dd20e05f9754"`);
        await queryRunner.query(`DROP TABLE "template_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbb3471dd14e54f1727bcc65ae"`);
        await queryRunner.query(`DROP TABLE "service_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dad6ad57fb4c094eea69aa9545"`);
        await queryRunner.query(`DROP TABLE "tables"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b0dd06eb0a7ea914010d769c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09ad80453a68e6263e0b73b36a"`);
        await queryRunner.query(`DROP TABLE "slug_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cce2a297871b91702b702bac2b"`);
        await queryRunner.query(`DROP TABLE "photo_wall"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bbc7822f5247b7de25eee9f0a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab221329a9f4c2111690d52f34"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54e1725163ede8bf2ce08874a6"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_398c05e4d6bf462a564518d763"`);
        await queryRunner.query(`DROP TABLE "invitation_versions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4f80ce3e8c902a041a0e67e9e"`);
        await queryRunner.query(`DROP TABLE "invitation_timelines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b935a633d89d654d89fe61146"`);
        await queryRunner.query(`DROP TABLE "invitation_photos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83a30ca2423c78e0368edca192"`);
        await queryRunner.query(`DROP TABLE "invitation_hosts"`);
        await queryRunner.query(`DROP TABLE "invitation_gifts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3be57c9efcf3f5d3e1f29b60ba"`);
        await queryRunner.query(`DROP TABLE "invitation_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_979d68c15b9cfa630e4e7b079a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8301ce4e44fd008d3fa52b1082"`);
        await queryRunner.query(`DROP TABLE "ai_scan_jobs"`);
    }

}
